// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klrlqnfkzetexxzgnayi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtscmxxbmZremV0ZXh4emduYXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTM5MjgsImV4cCI6MjA2MDIyOTkyOH0.06PBl3FJKVrNVJcVg6UWvB4024VKcvrlLxrG7vbunXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);